services:
  db:
    ports:
      # exposing the port for local dev; eg: docker compose -f docker-compose.dev.yml up db
      - "5432:5432"

  web:
    ports:
      - "8000:8000"

  # to test caddy setup in dev
  caddy:
    container_name: coasv-caddy
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./staticfiles:/srv/static
    networks:
      - coasv-network
    depends_on:
      - web

networks:
  coasv-network:
