# Generated by Django 5.0.7 on 2024-07-31 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coasc', '0014_alter_ac_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('stock', models.DecimalField(decimal_places=3, max_digits=12)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_credit_accounts', to='coasc.ac')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_debit_accounts', to='coasc.ac')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_credits', to='coasc.ac')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_debits', to='coasc.ac')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
            ],
        ),
    ]
