# Generated by Django 5.0.7 on 2024-08-01 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0014_alter_ac_cat'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coasc.transaction'),
        ),
    ]
