# Generated by Django 5.0.7 on 2024-08-01 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sale_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_reverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='original_sale',
            field=models.OneToOneField(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revert_sale', to='inventory.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='stock_increased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
