# Generated by Django 5.0.7 on 2024-08-01 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0014_alter_ac_cat'),
        ('inventory', '0003_sale_is_reverted_sale_original_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coasc.transaction'),
        ),
    ]
