# Generated by Django 5.1.1 on 2024-09-24 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coasc', '0014_alter_ac_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term', models.IntegerField(help_text='Loan term in months')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('FULLYPAID', 'Fully Paid'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20)),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=7)),
                ('purpose', models.TextField()),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coasc.member')),
            ],
        ),
        migrations.CreateModel(
            name='InterestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateTimeField()),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_payment_credits', to='coasc.ac')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_payment_debits', to='coasc.ac')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='coasc.transaction')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loan_management.loan')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateTimeField()),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='principal_payment_credits', to='coasc.ac')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='principal_payment_debits', to='coasc.ac')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loan_management.loan')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='coasc.transaction')),
            ],
        ),
    ]
