# Generated by Django 5.1.1 on 2024-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='minimum_payment',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=15),
        ),
    ]
