# Generated by Django 5.1.7 on 2025-06-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0003_alter_interestpayment_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='payment_frequency',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='term',
        ),
        migrations.AddField(
            model_name='interestpayment',
            name='term',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='current_term',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='principalpayment',
            name='term',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
