# Generated by Django 5.1.7 on 2025-09-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0004_remove_loan_end_at_remove_loan_payment_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestpayment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='principalpayment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
