# Generated by Django 5.1.7 on 2025-09-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0005_alter_interestpayment_id_alter_loan_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestpayment',
            name='term',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='current_term',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='minimum_payment',
        ),
        migrations.RemoveField(
            model_name='principalpayment',
            name='term',
        ),
    ]
