# Generated by Django 5.1.7 on 2025-10-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0006_remove_interestpayment_term_remove_loan_current_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='disbursed_amount',
        ),
    ]
