# Generated by Django 5.1.7 on 2025-10-05 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0007_remove_loan_disbursed_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('overdue', 'Overdue')], default='paid', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loan_management.loan')),
            ],
        ),
    ]
