# Generated by Django 5.1.7 on 2025-10-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0008_billingcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestpayment',
            name='billing_cycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='loan_management.billingcycle'),
            preserve_default=False,
        ),
    ]
