# Generated by Django 5.1.7 on 2025-10-06 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0009_interestpayment_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
