# Generated by Django 5.1.7 on 2025-10-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0010_billingcycle_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('paid', 'Paid'), ('defaulted', 'Defaulted')], default='pending', max_length=20),
        ),
    ]
