# Generated by Django 5.1.7 on 2025-10-12 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0011_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
