# Generated by Django 5.1.7 on 2025-10-13 14:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0014_alter_ac_cat'),
        ('loan_management', '0012_billingcycle_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loan_management.billingcycle')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payment_credits', to='coasc.ac')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payment_debits', to='coasc.ac')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loan_management.loan')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='coasc.transaction')),
            ],
        ),
    ]
