# Generated by Django 5.2.7 on 2025-11-03 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0013_feepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepayment',
            old_name='payment_date',
            new_name='payment_at',
        ),
        migrations.RenameField(
            model_name='interestpayment',
            old_name='payment_date',
            new_name='payment_at',
        ),
        migrations.RenameField(
            model_name='principalpayment',
            old_name='payment_date',
            new_name='payment_at',
        ),
        migrations.RemoveField(
            model_name='billingcycle',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='billingcycle',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interestpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interestpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='principalpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='principalpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
