# Generated by Django 5.2.7 on 2025-11-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0014_rename_payment_date_feepayment_payment_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcycle',
            name='period_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='period_start',
            field=models.DateField(),
        ),
    ]
